### ISSUE TITLE
SendInput dont work

### ISSUE THREAD

**Issue by devxart** [erinata/auto_click#2]
Hello, erinata!
I know, auto_click project is too old, but if you can, please, help me :).
I'm trying to use "type" and "key_stroke" methods, but no one is not working: no errors, no messages. Simply, no action.
After the seeking in source code, i'm find what they based on SendInput method.
Perhaps, this is depending of operating system and Ruby version? My current config:
Windows 7 x64 SP1 Corporate, ruby 2.0.0p481 (2014-05-08) [x64-mingw32]

**Comment by Vinculus** [comment]
I had the same problem.
I have fixed it with a x86 version of ruby.

**Comment by erinata** [comment]
Fixed in version 0.4.0
