### ISSUE TITLE
"LoadError: cannot load such file -- dl/import" when using Ruby 2.2 or later

### ISSUE THREAD

**Issue by kojix2** [erinata/auto_click#3]
DL has been removed from Ruby.
Please migrate code from DL to Fiddle.

**Comment by m1kal** [comment]
I made a fix for this issue: [https://github.com/erinata/auto_click/pull/4](https://github.com/erinata/auto_click/pull/4)

If you want to update the installed gem manually (until a new gem version is released) just edit the files in gem directory (in my case Ruby22/lib/ruby/gems/2.2.0/gems/auto_click-0.2.0/lib) and replace `DL` by `Fiddle`.

**Comment by erinata** [comment]
Thanks for the pull request.
