### ISSUE TITLE
Fixnum! nomethoderror on ruby 2.3.x

### ISSUE THREAD

**Issue by Atendam** [erinata/auto_click#5]
Hello, I am having an issue when i am passing a string into method type. 

the error i get is 
`undefined method `Fixnum!' for VirtualKey:Module (NoMethodError)`

I am using ruby 2.3.1 with plans to upgrade to 2.4.x soon. 

Was curious why Fixnum! was written. and if there were any plans to upgrade the gem for ruby compatibility. 

Thanks

**Comment by erinata** [comment]
Thanks. The ! is removed in the new version.
