### ISSUE TITLE
Windows 10 doesn't work

### ISSUE THREAD

**Issue by ckhung5** [erinata/auto_click#6]
I have tried.. It could move the mouse cursor but can't left click or right click

**Comment by hopelessdecoy** [comment]
You should try the version on my repository, I've made a lot of edits and fixes, plus it's working with the newest Ruby version and on Windows 10 (at least my windows 10).

**Comment by ckhung5** [comment]
@hopelessdecoy I tried it at 11 Jun and the mouse position is working but not the clicking.

**Comment by hopelessdecoy** [comment]
@ckhung5 This one yes but my version wasn't on here til just this week. I'm taking up this as a project and fixing expanding it: https://github.com/hopelessdecoy/auto_click
Download it and replace all the files of auto click with my files and you'll have my fixes and expansions!

**Comment by tensaix2j** [comment]
@ckhung5 if you are using 64bit windows you need to change the pack in input structure to "QLLLLQQ" .

**Comment by bellothornus** [comment]
> @ckhung5 if you are using 64bit of ruby you need to change the pack in input structure to "QLLLLQQ" .
> https://github.com/erinata/auto_click/blob/master/lib/auto_click/input_structure.rb . That kinda works for me.

Worked for me too, thanks, but why?? i need to know why changing the "LLLLLLL" to "QLLLLQQ" works.

**Comment by erinata** [comment]
Thanks for the comment. It's incorporated in the new version.
