### ISSUE TITLE
Auto click is not getting installed

### ISSUE THREAD

**Issue by mariyajolly** [erinata/auto_click#7]
Hi, I have installed ruby (version 2.0) and while trying to install the 'auto click' gem(in windows 7 and windows 10), I get the following error:-
ERROR:  Could not find a valid gem 'auto' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.org/latest_specs.4.8.gz)
ERROR:  Could not find a valid gem 'click' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.org/latest_specs.4.8.gz)

**Comment by erinata** [comment]
It seems that you are installing the gem"auto" and"click" , instead of "auto_click" ?
